CREATE TABLE `quotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`documentType` enum('quotation','invoice','payment_receipt') NOT NULL DEFAULT 'quotation',
	`quotationNo` varchar(128) NOT NULL,
	`clientName` varchar(256) NOT NULL,
	`clientAddress` text,
	`clientCountry` varchar(128),
	`clientTrn` varchar(128),
	`projectName` varchar(256),
	`quotationDate` varchar(32),
	`validUntil` varchar(32),
	`incoterms` varchar(32),
	`paymentTerms` varchar(256),
	`currency` varchar(8) NOT NULL DEFAULT 'USD',
	`notes` text,
	`paymentSchedule` text,
	`bankDetails` text,
	`products` text,
	`subtotal` int NOT NULL DEFAULT 0,
	`vatTotal` int NOT NULL DEFAULT 0,
	`total` int NOT NULL DEFAULT 0,
	`userId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotations_id` PRIMARY KEY(`id`)
);
