CREATE TABLE `periodic_inventory_lines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int NOT NULL,
	`odooLineId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`productCategory` varchar(255),
	`quantity` varchar(64) NOT NULL,
	`unit` varchar(64) NOT NULL,
	`grade` varchar(64),
	`weightRange` varchar(64),
	`notes` text,
	`syncedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `periodic_inventory_lines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `periodic_inventory_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`odooId` int NOT NULL,
	`name` varchar(64) NOT NULL,
	`date` date NOT NULL,
	`inventoryType` varchar(64) NOT NULL,
	`reportingUnit` varchar(64) NOT NULL,
	`productCategory` varchar(255),
	`grade` varchar(64),
	`weightRange` varchar(64),
	`country` varchar(128),
	`warehouse` varchar(255),
	`location` varchar(255),
	`state` enum('draft','supervisor_review','accounting_review','done','cancelled') NOT NULL,
	`supervisorReviewStatus` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`supervisorName` varchar(255),
	`supervisorReviewDate` timestamp,
	`accountingReviewStatus` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`accountantName` varchar(255),
	`accountingReviewDate` timestamp,
	`submittedBy` varchar(255),
	`submittedDate` timestamp,
	`totalProducts` int NOT NULL DEFAULT 0,
	`totalQuantity` varchar(64) NOT NULL DEFAULT '0',
	`notes` text,
	`syncedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `periodic_inventory_submissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `periodic_inventory_submissions_odooId_unique` UNIQUE(`odooId`),
	CONSTRAINT `periodic_inventory_submissions_name_unique` UNIQUE(`name`)
);
