CREATE TABLE `prop_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`installmentLabel` varchar(255),
	`amount` decimal(15,2),
	`currency` varchar(10) DEFAULT 'AED',
	`dueDate` date,
	`status` varchar(50) DEFAULT 'Pending',
	`paidAmount` decimal(15,2),
	`paidDate` date,
	`paymentMethod` varchar(100),
	`referenceNumber` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prop_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prop_properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`propertyName` varchar(255) NOT NULL,
	`developerName` varchar(255),
	`projectName` varchar(255),
	`country` varchar(100),
	`city` varchar(100),
	`district` varchar(255),
	`fullAddress` text,
	`latitude` decimal(10,6),
	`longitude` decimal(10,6),
	`unitType` varchar(100),
	`bedrooms` int,
	`bathrooms` int,
	`builtUpAreaSqm` decimal(10,4),
	`plotAreaSqm` decimal(10,4),
	`floorNumber` int,
	`unitNumber` varchar(100),
	`buildingName` varchar(255),
	`viewType` varchar(100),
	`furnishing` varchar(100),
	`parkingSpaces` int DEFAULT 0,
	`purchaseDate` date,
	`expectedDelivery` date,
	`actualDelivery` date,
	`deliveryStatus` varchar(100),
	`totalPrice` decimal(15,2),
	`currency` varchar(10) DEFAULT 'AED',
	`currentMarketValue` decimal(15,2),
	`valueLastUpdated` date,
	`purpose` varchar(100),
	`notes` text,
	`status` varchar(50) DEFAULT 'Active',
	`purchaseType` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prop_properties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prop_rental_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rentalId` int NOT NULL,
	`chequeNumber` varchar(100),
	`amount` decimal(15,2),
	`dueDate` date,
	`status` varchar(50) DEFAULT 'Pending',
	`paidDate` date,
	`bankName` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prop_rental_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prop_rentals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`propertyName` varchar(255) NOT NULL,
	`unitRef` varchar(100),
	`location` varchar(255),
	`landlord` varchar(255),
	`annualRent` decimal(15,2),
	`currency` varchar(10) DEFAULT 'AED',
	`startDate` date,
	`endDate` date,
	`status` varchar(50) DEFAULT 'Active',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prop_rentals_id` PRIMARY KEY(`id`)
);
